package com.example.shopshere.data.repository

import com.example.shopshere.domain.model.Product
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.tasks.await // This is an extension function to convert the Firebase callbacks to coroutines async/await
//This makes the code look synchronous and easier to read

/*
PRODUCT REPOSITORY
Repository Pattern - Acts as single source of truth for product data operations
Separates data access logic from UI/ViewModel
If we switch from Firebase to SQLite later, we only change this file
*/

class ProductRepository{
    private val firestore= FirebaseFirestore.getInstance() //this gets a reference to firebase firestore database
    /*
    getInstance()-->Singleton pattern means it uses the same connection
    private-->Only this class can access it
    val-->Immutable (cannot be reassigned)

    we could have also write:

    Dependency Injection (better for testing)
    class ProductRepository(private val firestore: FirebaseFirestore)

    This would allow injecting mock database for testing
    */

    /*
    MAIN FUNCTION TO FETCH ALL PRODUCTS

    suspend-->Marks function as coroutine (can be paused/resumed)
              Why: Firebase operations take time (network call) → prevents blocking UI thread
              Without suspend, you'd need callbacks (messier code)

    fun getProducts()-->Fetches all products from database
                        Repository's job is to provide data to ViewModels

    :List<Product>-->Returns a list of Product objects
                     Type safety - Kotlin knows what you're returning
    */
    suspend fun  getProducts():List<Product>{
        /*
        FETCHING DATA FROM FIRESTORE

        firestore.collection("products")-->Points to the "products" collection in Firestore

        Firestore Structure:
        Firestore Database
        └── products (collection)
            ├── doc1 (title: "Phone", price: 500, imageUrls: [...], stock: 10, ...)
            ├── doc2 (title: "Laptop", price: 1000, imageUrls: [...], stock: 5, ...)
            └── doc3 (...)

        .get()-->Fetches ALL documents in "products" collection
                 Returns: Task<QuerySnapshot> (Firebase's async result wrapper)

        .await()-->Waits for Firebase to finish fetching data
                   Converts Firebase's callback-based API to coroutines

        Alternative without coroutines (old style):
        firestore.collection("products").get()
            .addOnSuccessListener { snapshot -> /* use data */ }
            .addOnFailureListener { error -> /* handle error */ }

        val snapShot-->Stores the result
                       Type: QuerySnapshot (contains all documents)
        */
        val snapShot=firestore.collection("products").get().await()

        /*
        CONVERTING DOCUMENTS TO PRODUCT OBJECTS

        snapShot.documents-->List of all documents (raw Firebase data)
                             Type: List<DocumentSnapshot>

        .map{doc-->....}-->Transforms each document into a Product object
                           This is kotlin's functional programming style which is cleaner than the loops system

        Alternative can be (traditional loop):

        val products=mutableListOf<Product>()
        for(doc in snapshot.documents){
            products.add(Product(....))
        }

        return products

        Why map is better:
        - More concise (one expression vs multiple lines)
        - Functional style (preferred in Kotlin)
        - Immutable by default (returns new list)
        */

        return snapShot.documents.map{
            doc-> // This is a lambda parameter that means each document in the loop
            //rather than doc we could have used any name like document, item, etc.

            /*
            CREATING PRODUCT OBJECTS FROM FIRESTORE DOCUMENTS

            1-->id=doc.id
                Document's unique id from the firestore
                Example: "abc123xyz"
                This is auto-generated by Firestore when document is created

            2-->title=doc.getString("title")?:""
                Gets the "title" field from the document
                ?:-->Elvis operator i.e if null use "" instead
                Why-->This system prevents crashes if the field is missing
                      Better than doc.getString("title")!! which would crash on null

            3-->price=(doc.getLong("price")?:0).toInt()
                Gets the "price" field as number
                Why this complex syntax:
                    - Firestore stores the numbers as Long (64-bit integer)
                    - My Product model uses Int (32-bit integer)
                    - .toInt() converts Long to Int
                    - Elvis operator defaults to 0 if the price is missing
                Example: If price is 500 in Firestore, this gets 500L then converts to 500

            4-->description=doc.getString("description")?:""
                Gets the "description" field from the document
                Same pattern as title - defaults to empty string if missing

            5-->imageUrls=doc.get("imageUrls") as? List<String> ?:emptyList()
                This is the most complex one! Let's break it down:

                doc.get("imageUrls")-->Gets the field (unknown type - returns Any?)

                as? List<String>-->Safe cast to List<String>
                                   Returns null if the data is not a List<String>
                                   The ? makes it safe (won't crash on failure)

                ?: emptyList()-->If cast fails or field is null, use empty list instead

                Why so complex:
                - Firestore stores arrays, but we need type safety
                - Can't be sure the field exists or is correct type
                - Safe cast + Elvis operator = crash-proof code

                Alternative (riskier):
                doc.get("imageUrls") as List<String> // Crashes if not a list!

                Example data in Firestore:
                imageUrls: ["url1.jpg", "url2.jpg", "url3.jpg"]

            6-->stock=(doc.getLong("stock")?:0).toInt()
                Same pattern as price
                Gets stock count as number
                Firestore Long → Kotlin Int
                Defaults to 0 if missing

            7-->sellerId=doc.getString("sellerId")?:""
                Gets the ID of the seller who listed this product
                Links to the user document in "users" collection
                Used to identify who created/owns this product
                Defaults to empty string if missing
            */

            Product(
                id=doc.id, //Document's unique id from the firestore
                title=doc.getString("title")?:"",
                price=(doc.getLong("price")?:0).toInt(),
                description = doc.getString("description")?:"",
                imageUrls=doc.get("imageUrls") as? List<String> ?:emptyList(),
                stock=(doc.getLong("stock")?:0).toInt(),
                sellerId=doc.getString("sellerId")?:""
            )
        }
    }

    /*
    IS THIS STANDARD? ALTERNATIVES?

     This is Standard and Production-Ready!
    - Uses Repository Pattern (industry standard for data layer)
    - Uses Coroutines (modern Android best practice since 2019)
    - Handles null safety with Elvis operator (Kotlin best practice)
    - Functional programming with map (Kotlin idiomatic code)

     Alternative Approaches:

    1. Using Flow (Reactive Programming - for real-time updates):
    fun getProductsFlow(): Flow<List<Product>> = callbackFlow {
        val listener = firestore.collection("products")
            .addSnapshotListener { snapshot, error ->
                snapshot?.let { trySend(it.toProducts()) }
            }
        awaitClose { listener.remove() }
    }
    Pros: Real-time updates when products change in database
    Cons: More complex, uses more battery

    2. Using Callbacks (Old Android Style - before coroutines):
    fun getProducts(callback: (List<Product>) -> Unit) {
        firestore.collection("products").get()
            .addOnSuccessListener { callback(it.toProducts()) }
    }
    Cons: Callback hell, hard to read, no structured concurrency

    3. Adding Dependency Injection (Hilt/Koin - for scalability):
    @Singleton
    class ProductRepository @Inject constructor(
        private val firestore: FirebaseFirestore
    )
    Pros: Better for testing (can inject mock database), more scalable
    Cons: Requires additional setup and dependencies

    4. Adding Error Handling:
    suspend fun getProducts(): Result<List<Product>> {
        return try {
            val snapshot = firestore.collection("products").get().await()
            Result.success(snapshot.toProducts())
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    Pros: Better error handling, doesn't crash on network failure
    Cons: More boilerplate code

    SUMMARY TABLE:
    ┌─────────────────┬──────────────────────┬─────────────────────┐
    │ Feature         │ Purpose              │ Why This Way        │
    ├─────────────────┼──────────────────────┼─────────────────────┤
    │ suspend fun     │ Async operation      │ Prevents UI freeze  │
    │ .get().await()  │ Fetch all products   │ Cleaner than        │
    │                 │                      │ callbacks           │
    │ .map { doc-> }  │ Convert documents    │ Functional style    │
    │                 │                      │ (concise)           │
    │ ?: operator     │ Handle null values   │ Prevents crashes    │
    │ as? Type        │ Safe casting         │ Type safety         │
    └─────────────────┴──────────────────────┴─────────────────────┘
    */
}